# Generated by Django 3.2.12 on 2022-04-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uselog',
            name='imgsource',
            field=models.CharField(default='https://m.media-amazon.com/images/I/51M1Kv0ls2L._SS135_.jpg', max_length=64),
            preserve_default=False,
        ),
    ]
